const baseURL = process.env.REACT_APP_API_URL;
export const urlCourseCategories = `${baseURL}/courseCategories`;
export const urlPrivateLessonsCategories = `${baseURL}/privateLessonsCategories`;
export const urlCities = `${baseURL}/cities`;
export const urlTypes = `${baseURL}/types`;
export const urlCourses = `${baseURL}/courses`;
export const urlAccounts = `${baseURL}/accounts`;
export const urlRatings = `${baseURL}/ratings`;
export const urlCourseComments = `${baseURL}/courseComments`;